import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Pacifico } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/providers/QueryProvider";
import ProtectedRoute from "@/hooks/protectedRoutes";
const pacifico = Pacifico({
  variable:"--font-pacifico",
  weight:"400"
})
const inter = Inter({
    variable: "--font-inter",
  subsets: ["latin"],
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${geistSans.variable } ${pacifico.variable} ${inter.variable} ${geistMono.variable} antialiased`}
      > 
        <QueryProvider>
         {children}
        
        </QueryProvider>
       

      </body>
    </html>
  );
}
